- coordinator/api/models.py
- tests/test_sns.py
Uses proper formatting for sns messages.
> 🐛 Include default message in SNS

- coordinator/api/serializers.py
- coordinator/api/views/task.py
- coordinator/settings.py
- tests/settings.py
- tests/test_task_services.py
- tests/test_tasks.py
> ✨ Allow tasks to be filtered by release and service

- requirements.txt
Resolves security vuln in requirements.
> 📦 Upgrade cryptography package

- CHANGELOG.md
- coordinator/urls.py
- setup.py
Feature Emojis: ✨x2 ♻️x2 🐛x2 📦x1 📝x1
Feature Labels: [refactor](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/refactor) x3 [feature](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/feature) x2 [bug](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/bug) x2
- (#81) 📦 Upgrade cryptography package - @dankolbman
- (#60) ✨ Add status checks - @dankolbman
- (#80) ✨ Add enabled filter to task services - @dankolbman
- (#72) ♻️ Harden task failures - @dankolbman
- (#78) 🐛  Don't allow release in canceling to be canceled again - @dankolbman
- (#77) 📝 Update docs with failure and cancelation info - @dankolbman
- (#71) 🐛 Handle timeouts from services - @dankolbman
- (#69) ♻️ Use django-fsm - @dankolbman
> 🏷 Release 1.0.0

- docs/versions/README.md
> 📝 Design doc for versions

- README.md
Add some missing information about configuration and timeout behavior.
> 📝 Update readme

- CHANGELOG.md
- coordinator/urls.py
- setup.py
Feature Emojis: 🐛x3 ✨x2 ✏️x1 ⚡️x1 🔧x1
Feature Labels: [bug](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/bug) x5 [refactor](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/refactor) x1 [feature](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/feature) x1 [devops](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/devops) x1
- (#98) ✏️  s/published/complete/ - @dankolbman
- (#96) 🐛 Status check cancel release - @dankolbman
- (#95) ⚡️ Test refactoring - @dankolbman
- (#94) ✨ Check for staged and published states in task - @dankolbman
- (#93) 🐛 Increase study name size - @dankolbman
- (#85) ✨ Release Versions - @dankolbman
- (#90) 🐛 Fix model refactor - @dankolbman
- (#89) 🔧 Tune down …
> 🏷 Release 1.1.0

- CHANGELOG.md
- coordinator/urls.py
- setup.py
Feature Emojis: 🐛x2 👷x1 ✨x1
Feature Labels: [bug](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/bug) x2 [feature](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/feature) x1 [documentation](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/documentation) x1
- (#106) 🐛 Add missing return statement - @dankolbman
- (#103) 👷 Use module in Jenkinsfile - @dankolbman
- (#105) ✨ Filter by state - @dankolbman
- (#104) 🐛 Fix CircleCI badge in README - @dankolbman
> 🏷 Release 1.2.0

- requirements.txt
> ⬆️ Upgrade django version

- CHANGELOG.md
- coordinator/urls.py
- setup.py
Upgrade django to patch security vulnerability.
Feature Emojis: ⬆️x1
Feature Labels: [refactor](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/refactor) x1
- (#109) ⬆️ Upgrade django version - @dankolbman
> 🏷 Release 1.2.1

- coordinator/api/models/task.py
In case tasks report progress as a string with a `%`.
> ✏️ Coerce progress status from percent to int

- CHANGELOG.md
- coordinator/urls.py
- setup.py
Feature Emojis: ✨x1 ✏️x1 ♻️x1 🔊x1 📝x1
Feature Labels: [refactor](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/refactor) x2 [data model](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/data%20model) x1 [feature](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/feature) x1 [devops](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/devops) x1 [documentation](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/documentation) x1
- (#116) ✨ Release notes - @dankolbman
- (#115) ✏️ Coerce progress status from percent to int - @dankolbman
- (#114) ♻️ Use response content instead of json for log dumps - @dankolbman
- (#113) 🔊 Add failure logging - @dankolbman
- (#111) 📝 Add …
> 🏷 Release 1.3.0

- requirements.txt
Upgrades requests library to address the security [vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2018-18074).
> ⬆️ Upgrade requests dependency for vuln warning

- CHANGELOG.md
- coordinator/urls.py
- setup.py
Sends an Ego application JWT to task services so they may verify that the request originated from the coordinator
Feature Emojis: ✨x1 ⬆️x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/feature) x1 [refactor](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/refactor) x1
- (#119) ✨ Add ego jwt - @dankolbman
- (#118) ⬆️ Upgrade requests dependency for vuln warning - @dankolbman
> 🏷 Release 1.4.0

- CHANGELOG.md
- coordinator/urls.py
- setup.py
Feature Emojis: 🐳x1
Feature Labels: [refactor](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/refactor) x1
- (#127) 🐳 Docker refactor - @dankolbman
> 🏷 Release 1.5.1

- CHANGELOG.md
- coordinator/urls.py
- setup.py
Feature Emojis: 🖼x1 🐛x1
Feature Labels: [documentation](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/documentation) x1
- (#131) 🖼 Update logo - @dankolbman
- (#130) 🐛 Set default settings module for wsgi entry - @dankolbman
> 🏷 Release 1.5.2

- Dockerfile
- docker-compose.yml
> 🐳 Add dev stage to docker

- .circleci/config.yml
- pytest.ini
Add `pytest.ini` for quickly run pytest. 
closes #139
> ♻️ App pytest.ini for quick access pytest

- coordinator/api/serializers/release.py
- requirements.txt
- tests/conftest.py
- tests/test_auth.py
- tests/test_end_to_end.py
- tests/test_notes.py
- tests/test_tasks.py
Bums Django version to address security vulnerability.
> ⬆️ Bump Django version

- coordinator/settings/development.py
- coordinator/settings/production.py
Change `ego` to `EGO` in settings
> 🐛 Fix EGO settings

- bin/load_vault.sh
client secret is stored within the `data` object.
> 🐛 Fix typo in secret path

- bin/load_vault.sh
Reads secrets as raw strings, no `"` chars.
> ♻️ Read secrets as raw strings

- requirements.txt
Upgrades urllib to address vuln notification.
> ⬆️ Upgrade urllib3

- .circleci/config.yml
- Dockerfile
- coordinator/graphql/apps.py
- coordinator/graphql/releases.py
- coordinator/graphql/schema.py
- coordinator/middleware.py
- coordinator/settings/development.py
- coordinator/settings/production.py
- coordinator/settings/testing.py
- coordinator/urls.py
- requirements.txt
- tests/conftest.py
- tests/graphql/releases/test_queries.py
- tests/keys/jwks.json
Adds a minimal graphql api for querying releases.
> ✨Graphql API

- docs/index.rst
- docs/service_authentication.rst
Adds a page on how service authentication is performed by the release coordinator.
>  📝 Add page on service authentication

- coordinator/api/factories/event.py
- coordinator/graphql/events.py
- coordinator/graphql/schema.py
- tests/graphql/events/test_event_queries.py
Adds `allEvents` query to get events from the coordinator.
#196
> ✨ Add graphql query for events

- Dockerfile
- bin/entrypoint.sh
- coordinator/api/models/release.py
- coordinator/api/models/task.py
- coordinator/api/models/taskservice.py
- coordinator/authentication.py
- coordinator/settings/development.py
- coordinator/settings/production.py
- coordinator/settings/testing.py
- coordinator/tasks.py
- tests/test_end_to_end.py
- tests/test_task_services.py
- tests/test_tasks.py
This replaces the ego service token used to identify the Coordinator with an Auth0 service token using machine-to-machine auth.
Fixes #173
> ✨ Replace ego service token with Auth0

- coordinator/api/factories/study.py
- coordinator/graphql/schema.py
- coordinator/graphql/studies.py
- tests/graphql/studies/test_study_queries.py
Adds studies to the GraphQL schema.
> ✨ Add study queries

- coordinator/graphql/studies.py
- tests/graphql/studies/test_study_queries.py
Allows releases for a given study to be queried and filtered allowing the latest releases of given state to be retrieved.
> ✨ Add release subquery to studies

- coordinator/graphql/schema.py
- coordinator/graphql/task_services.py
- tests/graphql/task_services/test_create_task_service.py
- tests/graphql/task_services/test_update_task_service.py
Adds mutations to create and update task services.
Closes #222 
Closes #221
> ✨ Add Task Service mutations

- coordinator/tasks.py
Creates events whenever a request to a task service fails with information about why that request failed.
> 🔊 Create events for requests errors

- coordinator/middleware.py
- coordinator/settings/production.py
Corrects token checks in the Auth0 middleware.
> 🐛 Fix auth headers

- Jenkinsfile
Fixing library value to production library
> 👷 Changing Jenkins to Production library

- coordinator/api/views/task.py
- coordinator/authentication.py
- coordinator/settings/production.py
- coordinator/tasks.py
Adds logging for tasks for better observability and debugging.
> 🔊 Add task logging

- coordinator/settings/production.py
Allows credentials in requests to the server.
> 🔧 Allow cookies in requests

- Dockerfile
- coordinator/graphql/schema.py
- coordinator/version_info.py
Add query to return information about the current application version.
Closes #237
> ✨ Add status query

- .circleci/config.yml
- dev-requirements.txt
> 👷 Add codacy coverage

- coordinator/graphql/releases.py
- tests/graphql/releases/test_update_release.py
Allows editing of a release's name and description.
> ✨ Add mutation to edit release

- .circleci/config.yml
- docker-compose.yml
Build images and push to dockerhub from circle.
> 🐋 Push images to dockerhub

- coordinator/api/factories/release.py
Fixes release factory by randomly choosing a study to make the release for.
> 🐛 Fix release factory

- coordinator/settings/development.py
- coordinator/settings/production.py
- coordinator/settings/testing.py
> 🔧 Add SSL setting to RQ config

- CHANGELOG.md
- release_maker_cfg.json
- Emojis: 🔧 x3, 🐛 x1, 🏭 x1, 👷 x1, ⬆️ x1, 🤡 x1
- Categories: Other Changes x5, Fixes x1, Ops x2
- [#268](https://github.com/kids-first/kf-api-release-coordinator/pull/268) - 🔧 Added JenkinsfileWorker - [e8caed93](https://github.com/dankolbman/kf-api-release-coordinator/commit/e8caed9307d0eeb0b2b24cae03049a7a28c57a6f) by [alubneuski](https://github.com/alubneuski)
- [#267](https://github.com/kids-first/kf-api-release-coordinator/pull/267) - 🔧 Updated to standard deploy - [f6906748](https://github.com/dankolbman/kf-api-release-coordinator/commit/f69067486f46e61af5459672ba6399cacb4ccf1d) by [alubneuski](https://github.com/alubneuski)
- [#262](https://github.com/kids-first/kf-api-release-coordinator/pull/262) - 🔧 Add SSL setting to RQ config - …
> 🏷 Release 1.9.1

- CHANGELOG.md
- Emojis: 🔧 x2
- Categories: Other Changes x2
- [#272](https://github.com/kids-first/kf-api-release-coordinator/pull/272) - 🔧 Removed IAM and added SNS - [6942a096](https://github.com/dankolbman/kf-api-release-coordinator/commit/6942a0968dc8628b6c3a6dcc68faf8a966e61d6a) by [alubneuski](https://github.com/alubneuski)
- [#270](https://github.com/kids-first/kf-api-release-coordinator/pull/270) - 🔧 Update CORs whitelist for netlify - [8485b724](https://github.com/dankolbman/kf-api-release-coordinator/commit/8485b7249890c96680ba5d69255003a4a3b717ea) by [dankolbman](https://github.com/dankolbman)
> 🏷 Release 1.9.2

- coordinator/tasks.py
Includes studies in the release in actions sent to services.
> ✨ Include studies when communicating with tasks

- CHANGELOG.md
- Emojis: ✨ x1, 🔧 x1, ? x2
- Categories: Additions x1, Other Changes x3
- [#278](https://github.com/kids-first/kf-api-release-coordinator/pull/278) - ✨ Include studies when communicating with tasks - [b9fcb426](https://github.com/dankolbman/kf-api-release-coordinator/commit/b9fcb426a28ef3881bc16f77c5ed3ca4d77b0fd8) by [dankolbman](https://github.com/dankolbman)
- [#276](https://github.com/kids-first/kf-api-release-coordinator/pull/276) - 🔧 Add some log to troubleshoot issues with auth0 - [d0054810](https://github.com/dankolbman/kf-api-release-coordinator/commit/d0054810e2df7cd80bc44aca7c9c1cc765e1ad63) by [jecos](https://github.com/jecos)
- [#275](https://github.com/kids-first/kf-api-release-coordinator/pull/275) -  Update JenkinsfileWorker - …
> 🏷 Release 1.9.3
