bin/worker.conf
Increases number of workers per container to account for blocking network requests in python.
=> 🔧 Increase number of rq workers per container

coordinator/settings.py
Tasks should not take very long to complete as they are only responsible for sending web requests and updating the database.
=> 🔧 Decrease worker timeout for queues

bin/worker.conf
10 worker procs was saturating the container's memory. Cutting it in half.
=> 🔧 Tune down numprocs to utilize less memory

coordinator/api/models/task.py, coordinator/settings.py
Takes care of `staged` and `published` transitions during status checks.
Should be merged with code in the task view file eventually.
=> ✨ Check for staged and published states in task

coordinator/api/views/release.py, coordinator/api/views/task.py, tests/test_releases.py, tests/test_tasks.py
Allows releases and tasks to be filtered by state.
This means that searching for `/releases?state=published` will return a descending list of published releases and will be able to provide the latest available version.
Fixes #102
=> ✨ Filter by state

coordinator/tasks.py
Use `response.content` as `response.json()` may not always be available.
=> ♻️ Use response content instead of json for log dumps

coordinator/api/models/taskservice.py, tests/test_end_to_end.py, tests/test_task_services.py
Includes Ego JWT when checking status of a task service.
=> 🔧 Include jwt in Authorization header in requests to task's /status

Dockerfile
`Django-rq` has not released an update that changes an `async` naming conflict which breaks when trying to install under python 3.7. This pins the docker container to using 3.6 to avoid this conflict until it has been released.
=> 📌 Set python to version 3.6 in Dockerfile

requirements.txt
Redis 3.0.0 broke rq and so needs to be pinned until it is fixed.
=> 📌 Pin redis requirements

requirements.txt
Addresses security vuln in 1.22.
=> ⬆️ Bump urllib3 dependency

CHANGELOG.md, coordinator/urls.py, setup.py
Feature Emojis: 📌x2 ✨x1 ⬆️x1 🔧x1
Feature Labels: [bug](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/bug) x3 [feature](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/feature) x2 [refactor](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/refactor) x1
- (#122) ✨ Adds last_published fields to study model - @dankolbman
- (#126) ⬆️ Bump urllib3 dependency - @dankolbman
- (#125) 📌 Pin redis requirements - @dankolbman
- (#123) 📌 Set python to version 3.6 in Dockerfile - @dankolbman
- (#121) 🔧 Include jwt in Authorization header in requests to task's /status - @dankolbman
=> 🏷 Release 1.5.0

coordinator/wsgi.py
The default django settings module was wrong when launched through wsgi entry point through gunicorn.
=> 🐛 Set default settings module for wsgi entry

setup.cfg
Removes `setup.cfg` which is a duplicate of the contents of `pytest.ini`.
=> 🔥 Remove setup.cfg

bin/dev_entrypoint.sh, bin/dev_worker.sh, docker-compose.yml
Runs the worker process in periodic burst mode to to allow code changes during development.
Renames the dev entrypoint to be consistent with other projects.
=> 🔧 Improve docker-compose for development

pytest.ini
Jenkins fails pep8 because the -config repo files are not being ignored.
=> 🙈 Ignore ci files in jenkins

coordinator/settings/testing.py
The `testing` settings did not have all the correct apps installed that development and production had, which caused things to fail when running with `testing`.
=> 🐛 Update testing with correct apps

coordinator/settings/development.py, coordinator/settings/production.py, coordinator/settings/testing.py
Static paths are generated relative to the settings path, which got relocated to within the `coordinator` directory. This updates the static path to use the parent directory.
=> 🐛 Fix static paths

dev-requirements.txt, pytest.ini
Discovered that the `pep8` package was replaced with `pycodestyle` almost 5 years ago by direct orders from the BDFL.... oops.
=> 🔥 Replace pep8 with codestyle

coordinator/api/models/release.py, coordinator/api/models/task.py, tests/failures/test_fail_cancel_release.py
Releases were attempting to re-enter canceling state and were thus raising an error before being able to enqueue a task to get them out of that state.
This allows releases to change to `canceling` state cyclically so that the `cancel_release` task may be called to move the release to the `canceled` or `failed` state.
Fixes #136
=> 🐛 Allow releases to re-enter cancelling state

CHANGELOG.md, coordinator/urls.py, setup.py
Feature Emojis: 🐛x6 ♻️x4 🔥x2 🔧x2 ✨x1 🙈x1 ⬆️x1 🐳x1
/kids-first/kf-api-release-coordinator/labels/refactor) x8 [t/kf-a](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/devops) x5 [/kf-api](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/feature) x1
evops) x5 [feature](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/feature) x1
- (#159) ♻️ Read secrets as raw strings - @dankolbman
- (#158) 🐛 Fix typo in secret path - @dankolbman
- (#157) 🐛 Fix EGO settings - @XuTheBunny
- (#156) 🐛 Allow releases to re-enter cancelling state - @dankolbman
- (#155) ♻️ Store Ego service token for coordinator in cache - @XuTheBunny
- (#154) 🔥 Replace pep8 with codestyle - @dankolbman
- (#152) ♻️ Load secrets directly from vault - …
=> 🏷 Release 1.5.3

coordinator/api/views/release.py, coordinator/api/views/task_service.py, coordinator/authentication.py, coordinator/permissions.py, coordinator/settings/development.py, coordinator/settings/production.py, coordinator/settings/testing.py, tests/test_auth.py
Adds authentication class for Auth0 token validation. This relies on the `accessToken` being sent to the coordinator to contain these claims:
- `https://kidsfirstdrc.org/groups`
- `https://kidsfirstdrc.org/roles`
- `https://kidsfirstdrc.org/permissions`
These will be translated to ego equivalents.
Future refactoring should be made to make permission checks consistent by returning actual `User` models from the authentication classes.
=> ✨ Add auth0 token validation

coordinator/settings/production.py
Allows traffic from netlify to the coordinator API.
=> 🔧 Add netlify to CORS whitelist

tests/test_auth.py
A user cannot access the study releases if not authenticated
=> ✅ Add test for unauthed user cannot access study releases

bin/dev_entrypoint.sh
Get database host from the environment, if not specified, default to `pg`
closes #163
=> ♻️ Refactor for getting db host from environment

CHANGELOG.md, setup.py
Support auth0 token validation.
Feature Emojis: ⬆️x3 ♻️x1 ✅x1 🔧x1 ✨x1
Feature Labels: [refactor](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/refactor) x4 [feature](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/feature) x2 [devops](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/devops) x1
- (#170) ⬆️ Bump django from 2.1.9 to 2.1.10 - @dependabot[bot]
- (#169) ⬆️ Bump django from 2.1.7 to 2.1.9 - @dependabot[bot]
- (#168) ⬆️ Upgrade urllib3 - @dankolbman
- (#165) ♻️ Refactor for getting db host from environment - @XuTheBunny
- (#164) ✅ Add test for unauthed user cannot access study releases - @XuTheBunny
- (#162) 🔧 Add netlify to CORS whitelist - @dankolbman
- (#160) ✨ Add auth0 token validation - …
=> 🏷 Release 1.6.0

.circleci/config.yml
Removes all but the .git directory when clearing files for the `gh-pages` branch.
Ignores CI builds for the `gh-pages` branch.
=> 👷 Update gh-pages build

requirements.txt
Bumps requests and removes the hard dependency on urllib3 which was
causing version-incompatabilty issues with requests.
=> ⬆️ Bump requests version

coordinator/api/views/task.py, tests/test_tasks.py
Disables the delete action on tasks so that they may not be deleted.
Fixes #180
=> 🐛 Don't allow tasks to be deleted

coordinator/permissions.py, tests/test_permissions.py
Disables permission checking for the status_checks endpoints so that cloudwatch may trigger checks unauthenticated.
=> 🔓 Disable permissions for status checks

coordinator/api/factories/task_service.py, coordinator/graphql/schema.py, coordinator/graphql/task_services.py, tests/graphql/task_services/test_task_service_queries.py
Adds `allTaskServices` and `taskService` queries to get task services using graphql.
Closes #197
=> ✨ Add queries for task services

coordinator/api/factories/release_note.py, coordinator/graphql/release_notes.py, coordinator/graphql/schema.py, tests/graphql/release_notes/test_release_note_queries.py
Adds an `allReleaseNotes` query to get release notes via the graphql api.
Closes #198
=> ✨ Add graphql query for release notes

requirements.txt
This fixes the many `RemovedInDjango30Warning: Remove the context parameter from VersionField.from_db_value(). Support for it will be removed in Django 3.0.` warnings that occur during testing.
=> ⬆️ Upgrade semantic-version package

coordinator/urls.py
Removes csrf checking for the graphql endpoint.
=> 🔒 Exempt graphql endpoint from csrf

CHANGELOG.md, setup.py
Add Sphinx documentation site and read-only GraphQL api.
Feature Emojis: ✨x6 ⬆️x3 📝x2 🐛x2 🔒x1 x1 Fixx1 🏭x1 🔓x1 ✨Graphqlx1 ♻️x1 👷x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/feature) x7 [refactor](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/refactor) x6 [documentation](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/documentation) x3 [bug](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/bug) x3 [devops](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/devops) x2
- (#218) ✨ Add study queries - @dankolbman
- (#216) 🔒 Exempt graphql endpoint from csrf - @dankolbman
- (#209) ✨ Replace ego service token with Auth0 - @dankolbman
- …
=> 🏷 Release 1.7.0

coordinator/graphql/releases.py, coordinator/graphql/schema.py, tests/graphql/releases/test_cancel_release.py, tests/graphql/releases/test_create_release.py, tests/graphql/releases/test_publish_release.py
Adds mutations for creating, publishing, and canceling releases.
Closes #201 
Closes #202 
Closes #203
=> ✨ Graphql release mutations

coordinator/api/views/studies.py, coordinator/dataservice.py, coordinator/graphql/schema.py, coordinator/graphql/studies.py, tests/graphql/studies/test_study_sync.py, tests/test_studies.py
Adds syncStudies mutation and abstracts the sync functionality so that it may be shared between the rest and graphQL apis.
Closes #225
=> ✨ Add syncStudies mutation

coordinator/graphql/task_services.py
Only attempts to validate a service's url when it changes. Thisallows the service to disabled and otherwise updated when its endpoint is not functioning.
=> ♻️ Only validate url when changed

coordinator/authentication.py, coordinator/tasks.py
Returns empty header if a service token failed to be retrieved from auth0 and uses correct reference to task service when creating an event.
=> 🐛 Fix task events

coordinator/graphql/releases.py, tests/graphql/releases/test_publish_release.py
Delays the state transition until the task worker picks up the actual action of publishing the release.
=> 🐛 Don't change to publishing state immediately

coordinator/tasks.py
=> 🐛 Fix error message

coordinator/permissions.py, tests/failures/test_fail_run.py, tests/test_end_to_end.py, tests/test_permissions.py
Restricts updates to tasks to admins only.
Closes #178
=> 🔒 Make task updates protected

CHANGELOG.md, setup.py
Add mutations for GraphQL api.
Feature Emojis: ✨x6 🐛x4 🔊x2 🔒x1 🖼x1 🔧x1 👷x1 ♻️x1
Feature Labels: [feature](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/feature) x9 [bug](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/bug) x3 [devops](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/devops) x2 [refactor](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/refactor) x2 [documentation](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/documentation) x1
- (#239) ✨ Add status query - @dankolbman
- (#238) 🔒 Make task updates protected - @dankolbman
- (#235) 🖼 Update readme - @dankolbman
- (#236) 🔧 Allow cookies in requests - @dankolbman
- (#234) 🔊 Add task logging - …
=> 🏷 Release 1.8.0

docker-compose.yml
Updates the port to 5001 which is the standard port assigned to the coordinator in the data stack.
=> 🔧 Remap port to standard coordinator service port

coordinator/authentication.py, coordinator/settings/production.py, requirements.txt
Replaces the default in memory cache to instead use redis as a backend.
This ensures that all tasks and the webserver can use the same token without unecessary calls to Auth0.
Closes #244
=> 🔧 Store cache in redis

coordinator/api/models/release.py, coordinator/api/models/study.py, coordinator/api/views/studies.py, tests/graphql/studies/test_study_queries.py, tests/test_studies.py
Adds `related_name` to the study-release relationship so that the releases field is correctly resolved instead of being mapped to the `eleaseSet`field that is otherwise generated.
=> 🐛 Add releated_name to release relationship

coordinator/graphql/release_notes.py, coordinator/graphql/schema.py, tests/graphql/release_notes/test_create_release_notes.py, tests/graphql/release_notes/test_remove_release_notes.py, tests/graphql/release_notes/test_update_release_notes.py
Adds `createRelaseNote`, `editReleaseNote`, and `removeReleaseNote` mutations.
=> ✨ Add release note mutations

coordinator/graphql/release_notes.py, tests/graphql/release_notes/test_remove_release_notes.py
Prevents re-saving a release note after it has been dropped from the database.
=> 🐛 Don't resave release note on remove

CHANGELOG.md, setup.py
Adds new mutations and changes cache to utilize redis.
Feature Emojis: 🔧x3 🐛x2 ✨x2 👷x1
Feature Labels: [devops](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/devops) x3 [bug](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/bug) x2 [feature](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/feature) x2 [refactor](https://api.github.com/repos/kids-first/kf-api-release-coordinator/labels/refactor) x1
- (#249) 🐛 Don't resave release note on remove - @dankolbman
- (#248) ✨ Add release note mutations - @dankolbman
- (#247) 🔧 Allow duplicate usernames accross users - @dankolbman
- (#241) 🐛 Add releated_name to release relationship - @dankolbman
- (#246) ✨ Add mutation to edit release - @dankolbman
- (#245) 🔧 Store …
=> 🏷 Release 1.9.0

bin/dev_entrypoint.sh, coordinator/api/factories/release.py, docker-compose.yml, docker.env, requirements.txt, tests/graphql/releases/test_cancel_release.py
Fixes issues with the development environment starting in docker compose and makes fake data consistent with study creator.
=> 🤡 Improve mocks

.circleci/config.yml, .github/workflows/dockerimage.yml, .github/workflows/gh_release.yml
Builds and publishes a Docker image with GitHub actions to Dockerhub. This replaces the build and publish step in the circleci workflow to be consistent with the study creator CI.
=> 👷 Publish to dockerhub action
